/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ferreteria.sv.edu.unab.Presentacion;
import ferreteria.sv.edu.unab.Presentacion.paneles.CambiaPanel;

/**
 *
 * @author HP
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.uno.setSelected(true);
        //JOptionPane.showMessageDialog(null,pnlPrincipal.getSize());
        new CambiaPanel(pnlPrincipal, new ferreteria.sv.edu.unab.Presentacion.paneles.inicio());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMenu = new ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro();
        pnlMenu = new javax.swing.JPanel();
        uno = new ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro();
        rSButtonMetro2 = new ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro();
        rSButtonMetro4 = new ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro();
        rSButtonMetro5 = new ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro();
        rSButtonMetro6 = new ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro();
        bntReportes = new ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro();
        rSButtonMetro8 = new ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro();
        rSButtonMetro9 = new ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1460, 965));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/sv/edu/unab/Presentacion/img/menu.png"))); // NOI18N
        btnMenu.setColorNormal(new java.awt.Color(0, 0, 0));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel2.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        uno.setBackground(new java.awt.Color(153, 153, 153));
        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/sv/edu/unab/Presentacion/img/inicio.png"))); // NOI18N
        uno.setText("INICIO");
        uno.setColorHover(new java.awt.Color(0, 102, 102));
        uno.setColorNormal(new java.awt.Color(153, 153, 153));
        uno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        uno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        rSButtonMetro2.setBackground(new java.awt.Color(153, 153, 153));
        rSButtonMetro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/sv/edu/unab/Presentacion/img/registro.png"))); // NOI18N
        rSButtonMetro2.setText("REGISTROS");
        rSButtonMetro2.setColorHover(new java.awt.Color(0, 102, 102));
        rSButtonMetro2.setColorNormal(new java.awt.Color(153, 153, 153));
        rSButtonMetro2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonMetro2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });

        rSButtonMetro4.setBackground(new java.awt.Color(153, 153, 153));
        rSButtonMetro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/sv/edu/unab/Presentacion/img/compras.png"))); // NOI18N
        rSButtonMetro4.setText("COMPRAS");
        rSButtonMetro4.setColorHover(new java.awt.Color(0, 102, 102));
        rSButtonMetro4.setColorNormal(new java.awt.Color(153, 153, 153));
        rSButtonMetro4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonMetro4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        rSButtonMetro5.setBackground(new java.awt.Color(153, 153, 153));
        rSButtonMetro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/sv/edu/unab/Presentacion/img/ventas.png"))); // NOI18N
        rSButtonMetro5.setText("VENTAS");
        rSButtonMetro5.setColorHover(new java.awt.Color(0, 102, 102));
        rSButtonMetro5.setColorNormal(new java.awt.Color(153, 153, 153));
        rSButtonMetro5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonMetro5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        rSButtonMetro6.setBackground(new java.awt.Color(153, 153, 153));
        rSButtonMetro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/sv/edu/unab/Presentacion/img/inventario.png"))); // NOI18N
        rSButtonMetro6.setText("INVENTARIOS");
        rSButtonMetro6.setColorHover(new java.awt.Color(0, 102, 102));
        rSButtonMetro6.setColorNormal(new java.awt.Color(153, 153, 153));
        rSButtonMetro6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonMetro6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        bntReportes.setBackground(new java.awt.Color(153, 153, 153));
        bntReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/sv/edu/unab/Presentacion/img/reportes.png"))); // NOI18N
        bntReportes.setText("REPORTES");
        bntReportes.setColorHover(new java.awt.Color(0, 102, 102));
        bntReportes.setColorNormal(new java.awt.Color(153, 153, 153));
        bntReportes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bntReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntReportesActionPerformed(evt);
            }
        });

        rSButtonMetro8.setBackground(new java.awt.Color(153, 153, 153));
        rSButtonMetro8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/sv/edu/unab/Presentacion/img/ayuda.png"))); // NOI18N
        rSButtonMetro8.setText("AYUDA");
        rSButtonMetro8.setColorHover(new java.awt.Color(0, 102, 102));
        rSButtonMetro8.setColorNormal(new java.awt.Color(153, 153, 153));
        rSButtonMetro8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonMetro8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        rSButtonMetro9.setBackground(new java.awt.Color(153, 153, 153));
        rSButtonMetro9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ferreteria/sv/edu/unab/Presentacion/img/salir.png"))); // NOI18N
        rSButtonMetro9.setText("SALIR");
        rSButtonMetro9.setColorHover(new java.awt.Color(0, 102, 102));
        rSButtonMetro9.setColorNormal(new java.awt.Color(153, 153, 153));
        rSButtonMetro9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonMetro9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSButtonMetro2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
            .addComponent(rSButtonMetro4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonMetro5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonMetro6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bntReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonMetro8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonMetro9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(uno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetro4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetro5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetro6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetro8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetro9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
        );

        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
       /* int position=this.pnlMenu.getX();
        if(position > -1){
            Animacion.Animacion.mover_izquierda(0, -196, 2, 2, pnlMenu);
        }else{
            Animacion.Animacion.mover_derecha(-196, 0, 2, 2, pnlMenu);
        }*/
    }//GEN-LAST:event_btnMenuActionPerformed

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new ferreteria.sv.edu.unab.Presentacion.paneles.reg());
    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void bntReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntReportesActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new ferreteria.sv.edu.unab.Presentacion.paneles.Reportes());
    }//GEN-LAST:event_bntReportesActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new ferreteria.sv.edu.unab.Presentacion.paneles.inicio());
    }//GEN-LAST:event_unoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro bntReportes;
    private ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro btnMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro rSButtonMetro2;
    private ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro rSButtonMetro4;
    private ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro rSButtonMetro5;
    private ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro rSButtonMetro6;
    private ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro rSButtonMetro8;
    private ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro rSButtonMetro9;
    private ferreteria.sv.edu.unab.Presentacion.rsbuttom.RSButtonMetro uno;
    // End of variables declaration//GEN-END:variables
}
